/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const ABI_LOGO_URL = 'https://raw.githubusercontent.com/Hellomyfriend19/AcademicBureauOfInvestigation/refs/heads/main/ChatGPT%20Image%20Jun%208%2C%202026%20at%2003_29_45%20PM.png';

export const TICKER_MESSAGES = [
  'THREAT LEVEL: CRITICAL (EXPIRED LIBRARY BOOKS OVERDUE SEVERELY)',
  'WARNING: ACADEMIC INTEGRITY THRESHOLD EXCEEDED IN ROOM 402',
  'ALERT: INTEL REPORTS MULTIPLE CHATGPT COPY-PASTE INCIDENTS',
  'NOTICE: CITATION FORMATS BEING PARSED BY THE BOARD',
  'STATUS: ACTIVE INVESTIGATOR GROUPS SEARCHING THE CAMPUS QUAD',
  'STRIKE PROTOCOL ACTIVE: CITATION OUT OF APA ORDER IS AN OFFENSE',
  'WANTED FOR HIGH TREASON: FORGING AN ADVISOR\'S DISSERTATION SIGNATURE',
];
